### ISSUE TITLE
Falta un ID para los recambios

### ISSUE THREAD

**Issue by ap-ch** [ap-ch/AOS_Especificacion_Recambios#11]
@DCUPM @adominguezm19 @SofiaBrottonRuiz @mescribanob 
Tal y como lo tenemos planteado, el identificador sería el nombre del recambio.
Yo creo que se puede considerar el caso de que se quiera cambiar el nombre de un recambio (errata, cambio de especificaciones, etc.).

Le estoy dando vueltas a si deberíamos meter un identificador para los recambios tipo ID a raíz de esto. Requeriría de cambiar components/schemas y components/requestBodies.

**Comment by mescribanob** [comment]
Podemos poner el nombre del recambio como id si os parece bien

**Comment by adominguezm19** [comment]
Podría ser una buena opción para que luego sea más sencillo hacer las paths

**Comment by ap-ch** [comment]
> Podemos poner el nombre del recambio como id si os parece bien

Eso es lo que está puesto técnicamente ahora mismo, pero sería raro si tuviese espacios en blanco, por el tema de que hay un path que tiene que ser recambios/{recambio Id)

**Comment by ap-ch** [comment]
Cerrado con [561987c](https://github.com/ap-ch/AOS_Especificacion_Recambios/commit/561987cef61433a6a9f6196cea885532f1f01483)
